// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resenhando2.Api.Data;

#nullable disable

namespace Resenhando2.Api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241010141704_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resenhando2.Core.Entities.Review.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ReviewType");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("SpotifyId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Resenhando2.Core.Entities.Review.Review", b =>
                {
                    b.OwnsOne("Resenhando2.Core.ValueObjects.Review.ReviewText", "ReviewText", b1 =>
                        {
                            b1.Property<Guid>("ReviewId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ReviewBody")
                                .IsRequired()
                                .HasMaxLength(10000)
                                .HasColumnType("NVARCHAR(MAX)")
                                .HasColumnName("ReviewBody");

                            b1.Property<string>("ReviewTitle")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("ReviewText");

                            b1.HasKey("ReviewId");

                            b1.ToTable("Review");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId");
                        });

                    b.Navigation("ReviewText")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
